name: Deploy with approval

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  # Terraform version to use
  TERRAFORM_VERSION: 0.14.5
  # Tar file for artifact saving
  ARTIFACT_TAR: /tmp/ALL.tgz
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}
    - run: terraform init -input=false
    - run: terraform plan -input=false -out=terraform.plan
      id: plan
      # Need to use a tar file because the actions/upload-artifact@1 doesn't preserve the rights (https://github.com/actions/upload-artifact#limitations)
    - run: tar cfz ${{ env.ARTIFACT_TAR }} .
    - name: Upload Plan Artifact
      uses: actions/upload-artifact@v1
      with:
        name: ALL
        path: ${{ env.ARTIFACT_TAR }}

    - name: Display info
      run: |
        echo "terraform plan stdout: ${{ steps.plan.outputs.stdout }}"
        echo "terraform plan stderr: ${{ steps.plan.outputs.stderr }}"
        echo "terraform plan exitcode: ${{ steps.plan.outputs.exitcode }}"
  staging:
    needs: build
    name: Deploy to staging
    environment:
      name: staging
    runs-on: ubuntu-latest
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: ALL
    - run: find . -ls
    - run: tar xfz $(basename ${{ env.ARTIFACT_TAR }})
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}
    - run: terraform apply -input=false terraform.plan
