name: Deploy with approval

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  # Terraform version to use
  TERRAFORM_VERSION: 0.14.5
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}
    - run: terraform init -input=false
    - run: terraform plan -input=false -out=terraform.plan
      id: plan
    - run: tar cfz ALL.tgz .
    - name: Upload Plan Artifact
      uses: actions/upload-artifact@v1
      with:
        name: ALL
        path: ALL.tgz

    - name: Display info
      run: |
        echo "${{ steps.plan.outputs.stdout }}"
        echo "${{ steps.plan.outputs.stderr }}"
        echo "${{ steps.plan.outputs.exitcode }}"
  staging:
    needs: build
    name: Deploy to staging
    environment:
      name: staging
    runs-on: ubuntu-latest
    steps:
    - run: find . -ls
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: ALL
    - run: tar xfz ALL.tgz
    - run: find . -ls
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}
    - run: terraform apply -input=false terraform.plan
