name: Deploy with approval

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  # Terraform version to use
  TERRAFORM_VERSION: 0.14.5
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}
    - run: terraform init -input=false
    - run: terraform plan -input=false
      id: plan
    - name: Display info
      run: |
        echo "${{ steps.plan.outputs.stdout }}"
        echo "${{ steps.plan.outputs.stderr }}"
        echo "${{ steps.plan.outputs.exitcode }}"
  staging:
    needs: build
    name: Deploy to staging
    environment:
      name: staging
    runs-on: ubuntu-latest
    steps:
    - run: terraform plan -input=false
